In [1]:
import nltk

In [5]:
stop = nltk.corpus.stopwords.words('english')

In [6]:
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [7]:
from nltk.stem.porter import *


In [8]:
stemmer = PorterStemmer()

In [12]:
a = [[1,2,3],[3,4,5]]

In [13]:
a

[[1, 2, 3], [3, 4, 5]]

In [15]:
import numpy as np
b = np.array(a)

In [16]:
b

array([[1, 2, 3],
       [3, 4, 5]])

In [17]:
b[:,1]

array([2, 4])

In [18]:
b[:]

array([[1, 2, 3],
       [3, 4, 5]])

In [20]:
list(b[0,:])

[1, 2, 3]

In [21]:
b.shape

(2, 3)

In [27]:
c = b.reshape(6)

In [28]:
c

array([1, 2, 3, 3, 4, 5])