# 31-A


(1)

In [16]:
import numpy as np

In [25]:
a1 = np.zeros(10)

In [33]:
a1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [34]:
a1[4] = 1

In [35]:
a1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [38]:
a3 = np.arange(10,50)

In [39]:
a3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [42]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
a6 = np.random.rand(5,5)

In [50]:
a6

array([[0.36128503, 0.79331002, 0.493043  , 0.25023027, 0.7988845 ],
       [0.53000655, 0.13435859, 0.21690708, 0.10731772, 0.6919353 ],
       [0.97481471, 0.36552915, 0.9219427 , 0.76925411, 0.27206679],
       [0.33549513, 0.32645982, 0.71606562, 0.42089586, 0.08590962],
       [0.51717849, 0.52934432, 0.28670736, 0.99159831, 0.39633121]])

In [51]:
a6.max()

0.9915983118763345

In [52]:
a6.min()

0.08590961787946971

In [54]:
a7_1 = np.full((4,3),1)

In [56]:
a7_2 = np.random.rand(3,2)

In [57]:
a7 = np.matmul(a7_1 , a7_2)

In [58]:
a7

array([[1.59154294, 0.86638833],
       [1.59154294, 0.86638833],
       [1.59154294, 0.86638833],
       [1.59154294, 0.86638833]])

In [62]:
a8 = a7.transpose()

In [63]:
a8

array([[1.59154294, 1.59154294, 1.59154294, 1.59154294],
       [0.86638833, 0.86638833, 0.86638833, 0.86638833]])

In [68]:
a9_1 = np.arange(0,25).reshape(5,5)
a9_2 = np.arange(25,50).reshape(5,5)

In [70]:
a9_1+a9_2

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [71]:
a9_1-a9_2

array([[-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25]])


# 31-B

# Q1

In [ ]:
import numpy as np
import numpy.linalg as nl

a1_1 = np.array([[1,2],[3,4]])
a1_2 = np.array([[1, 2], [3, 4],[5,6]])

In [7]:
nl.eig(a1_1)


(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [8]:
nl.eig(a1_2)

LinAlgError: Last 2 dimensions of the array must be square

In [9]:
nl.svd(a1_1,full_matrices=True)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [10]:
nl.svd(a1_1,full_matrices=False)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [11]:
nl.svd(a1_2,full_matrices=True)

(array([[-0.2298477 ,  0.88346102,  0.40824829],
        [-0.52474482,  0.24078249, -0.81649658],
        [-0.81964194, -0.40189603,  0.40824829]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

In [12]:
nl.svd(a1_2,full_matrices=False)

(array([[-0.2298477 ,  0.88346102],
        [-0.52474482,  0.24078249],
        [-0.81964194, -0.40189603]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

# Q2


In [13]:
a2 = np.array([[7,1],[1,7]])


In [14]:
x,y = nl.eig(a2)

In [15]:
x,y

(array([8., 6.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

# Q3


In [73]:
a3 = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,2,0,4,4],[0,0,0,5,5],[0,1,0,2,2]])
U,S,V = nl.svd(a3,full_matrices=False)
U,S,V

(array([[-1.37599126e-01,  2.36114514e-02,  1.08084718e-02,
          9.90147543e-01, -1.26568534e-16],
        [-4.12797378e-01,  7.08343543e-02,  3.24254153e-02,
         -5.94088526e-02, -8.85034377e-01],
        [-5.50396503e-01,  9.44458057e-02,  4.32338870e-02,
         -7.92118034e-02,  4.24264069e-01],
        [-6.87995629e-01,  1.18057257e-01,  5.40423588e-02,
         -9.90147543e-02,  1.91609371e-01],
        [-1.52775087e-01, -5.91100963e-01, -6.53650843e-01,
         -9.73880310e-17,  4.77815907e-17],
        [-7.22165140e-02, -7.31311857e-01,  6.78209218e-01,
          4.93038066e-32, -7.10764783e-17],
        [-7.63875433e-02, -2.95550482e-01, -3.26825421e-01,
         -4.86940155e-17, -3.16203559e-17]]),
 array([1.24810147e+01, 9.50861406e+00, 1.34555971e+00, 1.84716760e-16,
        9.74452038e-33]),
 array([[-5.62258405e-01, -5.92859901e-01, -5.62258405e-01,
         -9.01335372e-02, -9.01335372e-02],
        [ 1.26641382e-01, -2.87705846e-02,  1.26641382e-01,
        

# Q4 

In [74]:
a4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])

In [77]:
a4 = a4.reshape(3,2,3)

In [78]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [82]:
for i in a4:
    for j in i:
        print('----')
        print(j)

----
[1 2 3]
----
[4 5 6]
----
[7 8 9]
----
[10 11 12]
----
[13 14 15]
----
[16 17 18]


# Q5 

In [83]:
a5 = np.array([[1,2],[3,4]])
b5 = np.array([[1,3],[2,4]])

In [84]:
np.dot(a5 , b5)

array([[ 5, 11],
       [11, 25]])

In [86]:
a5*b5

array([[ 1,  6],
       [ 6, 16]])

# Q6 

In [87]:
a6_1 = np.zeros((5,5))
a6_1 += np.arange(5)

In [88]:
a6_1

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [111]:
a6_2 = np.full((4,5,3),3)

In [112]:
np.cov(a6_2)

ValueError: m has more than 2 dimensions

In [113]:
a6_2

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])