In [2]:
import pandas as pd
from scipy.spatial.distance import cosine
import numpy as np
from scipy.sparse import csr_matrix
from __future__ import division
import matplotlib.pyplot as plt
from scipy import fft, arange, signal
import tensorflow as tf
%matplotlib inline

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
data = pd.read_csv("train_data_400.csv")
test = pd.read_csv("test_data_400.csv")

In [5]:
action_list = ['dws', 'jog', 'ups', 'wlk','sit','std']


#user_id=1
#t_data = data.loc[(data['action_id'].str.match(action_id+"$") ) & (data['user_id'] == user_id)]

total_list = []
curve_acc = 0.5

for action_id in action_list:
  print("-"*50,"\naction_id:",action_id)
  t_data = data.loc[(data['action_id'].str.match(action_id) )]
  t_data = t_data.drop(['action_id','user_id', 'time_50hz'], axis=1)
  t_data.pop(t_data.columns[0]) #remove index


  e = t_data.T
  #e = t_data
  c = np.corrcoef(e)

  e = np.abs(c)
  print(e.shape)
  #print(b)
  #print(*e, sep="\n")
  #print(e.shape)

  curve = curve_acc
  cnt_t = 0

  target = [1]*len(e)

  print(np.around(e, decimals=3))

  for i in range(len(e)):
      cnt = 0
      for j in range(i+1, len(e)):
          if e[i][j] > 1-curve and  target[j] == 1:
              cnt+=1
              target[j] = 0
              cnt_t += cnt
  #    print(cnt, end=", ")


  print("\n", cnt_t)
  print(np.sum(target))
  for i in range(len(target)):
    if target[i]:
      print(t_data.columns[i], end=', ')
  total_list.append(target)

  print("\n","-"*50)
  
print(*total_list, sep="\n")

-------------------------------------------------- 
action_id: dws
(11, 11)
[[1.    0.079 0.115 0.977 0.015 0.009 0.063 0.016 0.034 0.023 0.017]
 [0.079 1.    0.135 0.085 0.005 0.005 0.048 0.019 0.002 0.017 0.019]
 [0.115 0.135 1.    0.193 0.132 0.098 0.04  0.004 0.094 0.034 0.036]
 [0.977 0.085 0.193 1.    0.045 0.008 0.077 0.002 0.03  0.017 0.005]
 [0.015 0.005 0.132 0.045 1.    0.006 0.024 0.207 0.084 0.034 0.284]
 [0.009 0.005 0.098 0.008 0.006 1.    0.079 0.324 0.046 0.08  0.02 ]
 [0.063 0.048 0.04  0.077 0.024 0.079 1.    0.065 0.019 0.019 0.064]
 [0.016 0.019 0.004 0.002 0.207 0.324 0.065 1.    0.07  0.033 0.133]
 [0.034 0.002 0.094 0.03  0.084 0.046 0.019 0.07  1.    0.073 0.124]
 [0.023 0.017 0.034 0.017 0.034 0.08  0.019 0.033 0.073 1.    0.078]
 [0.017 0.019 0.036 0.005 0.284 0.02  0.064 0.133 0.124 0.078 1.   ]]

 1
10
attitude.pitch, attitude.yaw, gravity.x, gravity.z, rotationRate.x, rotationRate.y, rotationRate.z, userAcceleration.x, userAcceleration.y, userAcceleration.

In [6]:
t_data

attitude.pitch  attitude.yaw  gravity.x  gravity.y  gravity.z  \
84000        -1.051363      1.611548   0.496386   0.868100   0.001555   
84001        -1.051097      1.611145   0.496618   0.867968   0.001137   
84002        -1.050255      1.612825   0.497346   0.867550   0.001825   
84003        -1.053220      1.614236   0.494771   0.869021   0.001949   
84004        -1.054274      1.618206   0.493848   0.869542   0.003291   
84005        -1.054344      1.624517   0.493762   0.869576   0.006022   
84006        -1.055112      1.631102   0.493054   0.869955   0.008673   
84007        -1.055771      1.637890   0.492417   0.870280   0.011753   
84008        -1.056432      1.651168   0.491626   0.870606   0.018687   
84009        -1.055952      1.657187   0.491911   0.870369   0.021918   
84010        -1.055540      1.661548   0.492158   0.870166   0.024303   
84011        -1.056315      1.668141   0.491321   0.870548   0.027380   
84012        -1.056713      1.673553   0.490838   0.870744   0.029723   
84013        -1.056915      1.678808   0.490517   0.870843   0.032022   
84014        -1.056442      1.683719   0.490773   0.870611   0.034332   
84015        -1.056245      1.688824   0.490779   0.870514   0.036633   
84016        -1.056051      1.693527   0.490796   0.870418   0.038627   
84017        -1.056821      1.696550   0.490039   0.870797   0.039681   
84018        -1.056830      1.699745   0.489920   0.870801   0.041032   
84019        -1.057416      1.703343   0.489267   0.871089   0.042684   
84020        -1.057583      1.707168   0.488952   0.871172   0.044565   
84021        -1.057394      1.710697   0.488964   0.871078   0.046225   
84022        -1.056948      1.714003   0.489223   0.870860   0.047590   
84023        -1.056770      1.716088   0.489314   0.870772   0.048248   
84024        -1.056755      1.720334   0.489129   0.870764   0.050226   
84025        -1.058628      1.724739   0.487267   0.871684   0.052324   
84026        -1.059359      1.727654   0.486480   0.872042   0.053661   
84027        -1.060960      1.732934   0.484802   0.872824   0.056078   
84028        -1.062890      1.737707   0.482840   0.873765   0.058318   
84029        -1.064354      1.740149   0.481397   0.874476   0.059576   
...                ...           ...        ...        ...        ...   
125970       -1.542521      2.888843  -0.024212   0.999600  -0.014598   
125971       -1.539433     -3.134284  -0.021905   0.999508  -0.022439   
125972       -1.536531     -2.942839  -0.019015   0.999413  -0.028497   
125973       -1.533383     -2.793292  -0.016062   0.999300  -0.033780   
125974       -1.529331     -2.677166  -0.013457   0.999140  -0.039208   
125975       -1.524496     -2.594171  -0.011495   0.998928  -0.044834   
125976       -1.517960     -2.526752  -0.009883   0.998604  -0.051878   
125977       -1.510309     -2.478080  -0.008762   0.998171  -0.059812   
125978       -1.503715     -2.458319  -0.008946   0.997751  -0.066431   
125979       -1.498470     -2.459838  -0.010398   0.997386  -0.071511   
125980       -1.493692     -2.466313  -0.012312   0.997029  -0.076038   
125981       -1.491231     -2.437291  -0.011252   0.996836  -0.078681   
125982       -1.486555     -2.443006  -0.013195   0.996454  -0.083101   
125983       -1.483389     -2.399768  -0.010478   0.996182  -0.086665   
125984       -1.479669     -2.403131  -0.011568   0.995851  -0.090263   
125985       -1.476492     -2.402705  -0.012329   0.995557  -0.093353   
125986       -1.473385     -2.403682  -0.013310   0.995259  -0.096342   
125987       -1.469649     -2.406311  -0.014532   0.994889  -0.099924   
125988       -1.465329     -2.406410  -0.015579   0.994443  -0.104113   
125989       -1.460791     -2.401023  -0.016222   0.993955  -0.108579   
125990       -1.456033     -2.391867  -0.016679   0.993422  -0.113291   
125991       -1.451137     -2.381012  -0.017058   0.992849  -0.118149   
125992       -1.446166     -2.370667  -0.017583   0.992244  -0.123